### ISSUE TITLE
trezor signing: "AttributeError: 'NoneType' object has no attribute '_fill_missing'"

### ISSUE THREAD

**Issue by molecular** [Electron-Cash/Electron-Cash#957]
getting this when signing a tx with 2 inputs and one output using trezor based wallet 
this is new since I updated to f6bff0b9216d13ac8144c9e3f2c4222a59ac454a today.

```
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/gui/qt/util.py", line 580, in run
    result = task.task()
  File "/home/nick/bitcoin/electron-cash/lib/wallet.py", line 1291, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/trezor.py", line 58, in sign_transaction
    self.plugin.sign_transaction(self, tx, xpub_path)
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/trezor.py", line 296, in sign_transaction
    signed_tx = client.sign_tx(self.get_coin_name(), inputs, outputs, lock_time=tx.locktime)[1]
  File "/home/nick/bitcoin/electron-cash/plugins/trezor/clientbase.py", line 249, in wrapped
    return func(self, *args, **kwargs)
  File "/home/nick/bitcoin/electron-cash/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/home/nick/bitcoin/electron-cash/trezorlib/client.py", line 916, in sign_tx
    txes = self._prepare_sign_tx(coin_name, inputs, outputs)
  File "/home/nick/bitcoin/electron-cash/trezorlib/client.py", line 905, in _prepare_sign_tx
    txes[inp.prev_hash]._fill_missing()
AttributeError: 'NoneType' object has no attribute '_fill_missing'
```

maybe I'm using wrong trezorlib version (using 0.9.1)?

**Comment by molecular** [comment]
also happens in another trezor-based wallet I have

**Comment by molecular** [comment]
works with trezorlib 0.10.2. sorry

**Comment by plshalpBCH** [comment]
Hey @molecular I am a noob getting the same error on Ubuntu with my trezor. How do I update to trezorlib 0.10.2?

I've tried things like 

sudo apt-get update        # Fetches the list of available updates
sudo apt-get upgrade       # Strictly upgrades the current packages
sudo apt-get dist-upgrade  # Installs updates (new ones)

sudo apt remove python-trezor
sudo apt-get install python-trezor

sudo pip2 uninstall trezor
sudo pip2 install trezor

sudo pip uninstall trezor
sudo pip install trezor

and nothing seems to work.

**Comment by plshalpBCH** [comment]
When I run something like "sudo pip install trezor
I get

The directory '/home/fuckyou/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/fuckyou/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting trezor
  Downloading https://files.pythonhosted.org/packages/7c/85/14377da484c2c0c274778bcb8938c6a53ae737650c5641f87468e20be57c/trezor-0.10.0.tar.gz (482kB)
    100% |████████████████████████████████| 491kB 14.4MB/s 
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python2.7/dist-packages (from trezor) (20.7.0)
Requirement already satisfied: ecdsa>=0.9 in /usr/lib/python2.7/dist-packages (from trezor) (0.13)
Requirement already satisfied: mnemonic>=0.17 in /usr/local/lib/python2.7/dist-packages (from trezor) (0.18)
Requirement already satisfied: requests>=2.4.0 in /usr/local/lib/python2.7/dist-packages (from trezor) (2.18.4)
Requirement already satisfied: click>=6.2 in /usr/local/lib/python2.7/dist-packages (from trezor) (7.0)
Requirement already satisfied: pyblake2>=0.9.3 in /usr/local/lib/python2.7/dist-packages (from trezor) (1.1.2)
Requirement already satisfied: libusb1>=1.6.4 in /usr/local/lib/python2.7/dist-packages (from trezor) (1.6.6)
Requirement already satisfied: typing>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from trezor) (3.6.6)
Requirement already satisfied: pbkdf2 in /usr/lib/python2.7/dist-packages (from mnemonic>=0.17->trezor) (1.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor) (2017.7.27.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.4.0->trezor) (1.22)
Installing collected packages: trezor
  Running setup.py install for trezor ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-DONsF3/trezor/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-59_xRy/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    running prebuild
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-DONsF3/trezor/setup.py", line 113, in <module>
        'prebuild': PrebuildCommand,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-DONsF3/trezor/setup.py", line 64, in new_run
        self.run_command('prebuild')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-DONsF3/trezor/setup.py", line 45, in run
        with tempfile.TemporaryDirectory() as tmpdir:
    AttributeError: 'module' object has no attribute 'TemporaryDirectory'
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-DONsF3/trezor/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-59_xRy/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-DONsF3/trezor/

**Comment by molecular** [comment]
@plshalpBCH 

you're definitely on the right track...

> The directory '/home/fuckyou/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled

are you logged in as user "fuckyou"?

try "ls -l /home/fuckyou/.cache/pip/http" and look at the owner and permissions.

maybe you can just delete that cache? "rm -rf /home/fuckyou/.cache/pip"?

also you can look what's installed using "find /usr -type d | grep python | grep trezor"

I have a 

> /usr/lib/python3.7/site-packages/trezorlib

which is version 0.10.2, which I can see using "cat /usr/lib/python3.7/site-packages/trezorlib/__init__.py"

maybe you have some older version installed there (using your debian tools or whatever) that gets in the way. If so, delete it (using apt or whatever) or if nothing else helps using "rm"

**Comment by BCHPlsHalp2** [comment]
Hey @molecular thanks for the help. And yes that was what I was logged in as lol. I was able to figure it out using these instructions https://github.com/trezor/python-trezor/blob/master/README.md

 I think I needed to use pip3 instead so that I was using python 3. Could be and probably am totally wrong though.

Thanks again!
